// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementApi.Models;

namespace ProductManagementApi.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductManagementApi.Models.Product", b =>
                {
                    b.Property<int?>("HsnCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company");

                    b.Property<string>("Description");

                    b.Property<int?>("Igst");

                    b.Property<double?>("Mrp");

                    b.Property<string>("Name");

                    b.Property<string>("PartNumber");

                    b.Property<double?>("PuchaseWithTax");

                    b.Property<double?>("PurchaseWithoutTax");

                    b.Property<int?>("Qty");

                    b.Property<double?>("SellingPrice");

                    b.Property<int?>("Sgst");

                    b.HasKey("HsnCode");

                    b.ToTable("Products");

                    b.HasData(
                        new { HsnCode = 85365090, Company = "BOSCH", Description = "RBCSBC(BATTERY CUT)", Igst = 9, Mrp = 866.0, Name = "Battery Cut", PartNumber = "RBCSBC", PuchaseWithTax = 750.0, PurchaseWithoutTax = 650.0, Qty = 30, SellingPrice = 850.0, Sgst = 9 },
                        new { HsnCode = 85365060, Company = "TELCO", Description = "TX 88512WOS-AL (Bearing)", Igst = 9, Mrp = 1600.0, Name = "Bearing", PartNumber = "TX 88512WOS-AL", PuchaseWithTax = 1200.0, PurchaseWithoutTax = 1100.0, Qty = 10, SellingPrice = 1550.0, Sgst = 9 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
